EXEC msdb.dbo.sp_delete_database_backuphistory @database_name = N'Steedfix'
GO
USE [master]
GO
/****** Object:  Database [Steedfix]    Script Date: 09/30/2014 07:55:03 ******/
DROP DATABASE [Steedfix]
GO


CREATE DATABASE [Steedfix] ON  PRIMARY 
( NAME = N'Steedfix', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\Steedfix.mdf' , SIZE = 3072KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Steedfix_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\Steedfix_log.ldf' , SIZE = 1024KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [Steedfix] SET COMPATIBILITY_LEVEL = 100
GO
ALTER DATABASE [Steedfix] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Steedfix] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Steedfix] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Steedfix] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Steedfix] SET ARITHABORT OFF 
GO
ALTER DATABASE [Steedfix] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Steedfix] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [Steedfix] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Steedfix] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Steedfix] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Steedfix] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Steedfix] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Steedfix] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Steedfix] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Steedfix] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Steedfix] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Steedfix] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Steedfix] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Steedfix] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Steedfix] SET  READ_WRITE 
GO
ALTER DATABASE [Steedfix] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Steedfix] SET  MULTI_USER 
GO
ALTER DATABASE [Steedfix] SET PAGE_VERIFY CHECKSUM  
GO
USE [Steedfix]
GO
CREATE USER [Steedfix] FOR LOGIN [Steedfix]
GO
USE [Steedfix]
GO
EXEC sp_addrolemember N'db_owner', N'Steedfix'
GO

USE [Steedfix]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [Steedfix] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
